classrooms/urls.py
from django.urls import path, include

from . import views

app_name = 'class'

urlpatterns = [
    path('room/<slug:code>/', views.classroom, name='classroom'),
    path('room/<slug:code>/<slug:channel>', views.classroom, name='classroom'),
    path('create/', views.create_classroom, name='create_classroom'),
]

main/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

import classrooms

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('home', views.home, name='home'),
]

manthano/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('user/', include('users.urls', namespace='users')),
    path('class/', include('classrooms.urls', namespace='class')),
]

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth_views

import classrooms

from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.log_in, name='log_in'),
    path('sign-up/', views.sign_up, name='sign_up'),
    path('logout/', views.log_out, name='log_out'),
    path('profile/', views.profile, name='profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.db.models import CASCADE

class Classroom(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    schedule = models.ImageField(upload_to='uploads/schedule_%Y_%m_%d')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
    
class Channel(models.Model):
    name = models.CharField(max_length=255)
    group_name = models.CharField(max_length=100)

    classroom = models.ForeignKey('main.Classroom', on_delete=CASCADE, default='', related_name='channels')

    def __str__(self):
        return self.name
    
    

main/views.py
from django.shortcuts import render, redirect

from django.contrib.auth.decorators import login_required
from django.contrib import messages

@login_required(login_url='/user/login')
def home(request):
    return render(request, 'main/home.html')

main/templates/main/base.html
{% load static %}
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en">
  <head>
    {% block head %}
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>{% block title %}{% endblock %}</title>

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/1708a644c8.js" crossorigin="anonymous"></script>

		{% tailwind_css %}
    {% block style %}
    <style>
      body {
        background: rgb(21,32,55);
        background: linear-gradient(180deg, rgba(21,32,55,1) 40%, rgba(14,51,112,1) 100%);
        background-attachment: fixed;
      }
    </style>
    {% endblock %}
    {% endblock head %}
  </head>

  <body class="bg-gray-900 text-slate-200">
    {% if messages %}
      {% for message in messages %}
        <div class="fixed bottom-2 left-1/2 -translate-x-1/2 bg-neonblue-500 font-extrabold text-center justify-center border-slate-800 rounded-lg px-8 py-4" role="alert">{{ message }}</div>
      {% endfor %}
    {% endif %}
    
    <nav class="border-gray-200 bg-gray-900 shadow-2xl">
      <div class="relative flex w-full p-4">
        <a href="#" class="absolute mb-2 flex items-center">
          <img src="{% static 'main/media/logos/m-dark.png' %}" class="mr-3 h-12" alt="Manthano logo" />
        </a>
        <div class="ml-auto mr-auto flex flex-row h-10">
          {% include "main/menubar.html" %}
          <ul class="absolute right-0 top-1/2 flex -translate-y-1/2 flex-row">
            {% if user.is_authenticated %}
            <li>
              <a class="text-white bg-blue-700 hover:bg-gray-100 md:hover:bg-transparent block rounded py-2 pl-3 pr-3" href="{% url 'users:profile' %}">Logged in as <span class="fw-bold">{{ user.username }}</span></a>
            </li>
            <li>
              <a class="hover:bg-gray-100 md:hover:bg-transparent text-white block rounded py-2 pl-3 pr-3" href="{% url 'users:log_out' %}">Logout</a>
            </li>
            {% else %}
            <li>
              <a class="mx-4" href="{% url 'users:log_in' %}">Login</a>
            </li>
            <li>
              <a class="mx-4" href="{% url 'users:sign_up' %}">Register</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="mt-12 mb-20 flex justify-center">
      {% block content %}
        <div class="glassy bg-glass-500 bg-blue border-gray-700 relative w-3/4 rounded-md border bg-opacity-70 p-10 text-left text-2xl">
      {% endblock %}
      </div>
    </div>
  </body>
</html>

main/templates/main/home.html
{% extends 'main/base.html' %} {% block title %}
  Home Page
{% endblock %}
{% block content %}
  {{ block.super }}
  <h1 class="font-bold">Welcome!</h1>
  <p class="mt-6 text-base text-parag">Manthano is an application designed to
    help students with tools with the objective to assist them in the process of
    learning and undertanding a subject.</p>
{% endblock %}

main/templates/main/menubar.html
<ul class="bg-gray-800 border-gray-700 flex rounded-lg border h-10 pr-4 pl-4 font-bold">
    <li class="hover:bg-gray-800 hover:shadow-red-900 pl-3 pr-3 hover:scale-105 hover:shadow-lg hover:duration-75 hover:ease-in-out">
        <a class="hover:bg-gray-100 hover:text-gray-100 md:hover:bg-transparent text-gray-300 block rounded py-2 pl-3 pr-3" href="/home">Home</a>
    </li>
    <li class="hover:bg-gray-800 hover:shadow-green-900 pl-3 pr-3 hover:scale-105 hover:shadow-lg hover:duration-75 hover:ease-in-out">
        <a class="hover:bg-gray-100 hover:text-gray-100 md:hover:bg-transparent text-gray-300 block rounded py-2 pl-3 pr-3" href="{% if request.user.classroom %}{% url 'class:classroom' request.user.classroom.code %}{% else %}{% url 'class:create_classroom' %}{% endif %}">Classroom</a>
    </li>
    <li class="hover:bg-gray-800 hover:shadow-blue-900 pl-3 pr-3 hover:scale-105 hover:shadow-lg hover:duration-75 hover:ease-in-out">
        <a class="hover:bg-gray-100 hover:text-gray-100 md:hover:bg-transparent text-gray-300 block rounded py-2 pl-3 pr-3" href="/about">About</a>
    </li>
    <li class="hover:bg-gray-800 hover:shadow-amber-900 pl-3 pr-3 hover:scale-105 hover:shadow-lg hover:duration-75 hover:ease-in-out">
        <a class="hover:bg-gray-100 hover:text-gray-100 md:hover:bg-transparent text-gray-300 block rounded py-2 pl-3 pr-3" href="https://github.com/reszkojr/manthano">GitHub</a>
    </li>
    <li class="hover:bg-gray-800 hover:shadow-gray-500 pl-3 pr-3 hover:scale-105 hover:shadow-lg hover:duration-75 hover:ease-in-out">
        <a class="hover:bg-gray-100 hover:text-gray-100 md:hover:bg-transparent text-gray-300 block rounded py-2 pl-3 pr-3" href="/contribute">Contribute</a>
    </li>
</ul>